import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: [
      { find: '@', replacement: path.resolve(__dirname, './') },
      // Strip pinned versions from import specifiers generated by figma/shadcn exports
      { find: /@radix-ui\/react-([^@]+)@[^\s'\"]+/g, replacement: '@radix-ui/react-$1' },
      { find: /lucide-react@[^\s'\"]+/g, replacement: 'lucide-react' },
      { find: /class-variance-authority@[^\s'\"]+/g, replacement: 'class-variance-authority' },
      { find: /react-hook-form@[^\s'\"]+/g, replacement: 'react-hook-form' },
      { find: /react-resizable-panels@[^\s'\"]+/g, replacement: 'react-resizable-panels' },
      { find: /cmdk@[^\s'\"]+/g, replacement: 'cmdk' },
      { find: /input-otp@[^\s'\"]+/g, replacement: 'input-otp' },
      { find: /embla-carousel-react@[^\s'\"]+/g, replacement: 'embla-carousel-react' },
      { find: /recharts@[^\s'\"]+/g, replacement: 'recharts' },
      { find: /react-day-picker@[^\s'\"]+/g, replacement: 'react-day-picker' },
      { find: /vaul@[^\s'\"]+/g, replacement: 'vaul' },
      { find: /next-themes@[^\s'\"]+/g, replacement: 'next-themes' },
    ],
  },
})

