/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

// Ces valeurs sont désormais lues des variables d'environnement Vite.
// Définissez-les dans `.env.local` ou sur Vercel comme variables chiffrées.
export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID as string
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string